services:
  pi-emulator:
    image: justivo/pi-emulator:trixie
    build:
      context: ./pi-emulator
      args:
        KERNEL_BRANCH: rpi-6.12.y
        # As the folder name and the archived img file are different, 
        # i.e. DISTRO_FILE differs from DISTRO_IMG
        DISTRO_FILE: 2025-10-01-raspios-trixie-arm64-lite.img
        DISTRO_IMG: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02/2025-10-01-raspios-trixie-arm64-lite.img.xz
    entrypoint: []
    command:
      - bash
      - -c
      - |
        /app/run.py resize 8G -y
        /app/run.py start
    ports:
      - 2222:2222
    volumes:
      - ./dist:/dist

  ansible:
    image: justivo/ansible:latest
    build: .
    depends_on:
      - pi-emulator
    volumes:
      - ./ansible:/etc/ansible/playbooks
      - ./dist:/distro

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/30
          gateway: 172.16.1.1
