---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install PipeWire and all its dependancies
  ansible.builtin.apt:
    name:
      - pipewire
      - wireplumber
      - pipewire-pulse
      - pipewire-alsa
    state: present

- name: Install GStreamer and all its dependancies
  ansible.builtin.apt:
    name:
      - gstreamer1.0-tools
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
    state: present

- name: Install optional packages
  ansible.builtin.apt:
    name:
      - vim
    state: present
