---
- name: Change default keyboard layout to US
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBLAYOUT="
    line: 'XKBLAYOUT="us"'

- name: Automatically connect to SSID on boot
  ansible.builtin.template:
    src: templates/ssid.nmconnection.j2
    dest: "/etc/NetworkManager/system-connections/{{ wifi_ssid }}.nmconnection"
    mode: "600"

