---
- name: Configure authentication for Icecast
  ansible.builtin.replace:
    path: "{{ icecast_config_file }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop_control:
    label: "{{ item.name }}"
  loop:
    - name: Change source password
      regexp: "<source-password>.*</source-password>"
      replace: "<source-password>{{ user_password }}</source-password>"

    - name: Change relay password
      regexp: "<relay-password>.*</relay-password>"
      replace: "<relay-password>{{ user_password }}</relay-password>"

    - name: Change admin password
      regexp: "<admin-password>.*</admin-password>"
      replace: "<admin-password>{{ root_password }}</admin-password>"

- name: Start the Icecast service
  ansible.builtin.systemd_service:
    name: icecast2
    enabled: true
