emulated:
  hosts:
    raspberrypi:
      ansible_host: pi-emulator
      ansible_connection: ssh
      ansible_user: root
      # ansible_password: raspberry
      ansible_port: 2222
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
