emulated:
  hosts:
    raspberrypi:
      ansible_host: pi-emulator
      ansible_connection: ssh
      ansible_user: root
      # Initially the emulated os does not have root password
      # but when you want to make modification on top of existing one
      # this is crucial
      ansible_password: "{{ root_password }}"
      ansible_port: 2222
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
